-- EXPAND: a surrogate key for address and a flag for the primary address.
-- Nothing changes for app v1: customer_id is still the PK, so still max one row per customer.

-- Identity column on an existing table: every row needs its own value -> table rewrite.
-- Acceptable for a small table. On a large one: add a nullable bigint, SET DEFAULT
-- nextval(...) for new rows, backfill in batches (see D13 for the same idea with UUIDs).
ALTER TABLE address ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;

-- Constant default -> no rewrite (A3). Every existing address is the customer's only one = primary.
ALTER TABLE address ADD COLUMN is_primary boolean NOT NULL DEFAULT true;
