-- customer.id is an INTEGER and referenced by orders.customer_id.
-- The identity sequence is close to the int limit (2,147,483,647): inserts will soon fail with
-- "nextval: reached maximum value of sequence". Goal: widen both columns to bigint without downtime.
CREATE TABLE customer (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL
);

CREATE TABLE orders (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id integer       NOT NULL REFERENCES customer (id),
    amount      numeric(12,2) NOT NULL
);
CREATE INDEX orders_customer_id_idx ON orders (customer_id);

INSERT INTO customer (email)
SELECT 'user' || g || '@example.com' FROM generate_series(1, 20000) AS g;

INSERT INTO orders (customer_id, amount)
SELECT 1 + (g % 20000), round((random() * 500 + 1)::numeric, 2)
FROM generate_series(1, 200000) AS g;

-- Fast-forward the sequence: only ~1,000 ids left before the int limit.
ALTER TABLE customer ALTER COLUMN id RESTART WITH 2147482600;
INSERT INTO customer (email) VALUES ('near-the-limit@example.com');
