-- THE SWAP: one transaction, metadata-only statements.
-- Everything expensive (backfill, index builds, validation) happened before, so the ACCESS EXCLUSIVE locks last milliseconds.
SET LOCAL lock_timeout = '5s';

-- Remember where the identity sequence is before it gets dropped with the old column.
CREATE TEMP TABLE _identity_position ON COMMIT DROP AS
SELECT greatest(
           pg_sequence_last_value(pg_get_serial_sequence('customer', 'id')::regclass),
           (SELECT max(id) FROM customer)
       ) AS last_value;

-- 1. Stop syncing.
DROP TRIGGER customer_sync_id_new ON customer;
DROP TRIGGER orders_sync_customer_id_new ON orders;
DROP FUNCTION customer_sync_id_new();
DROP FUNCTION orders_sync_customer_id_new();

-- 2. move NOT NULL without a scan (validated CHECKs prove it), then drop the helper CHECKs.
ALTER TABLE customer ALTER COLUMN id_new SET NOT NULL;
ALTER TABLE orders   ALTER COLUMN customer_id_new SET NOT NULL;
ALTER TABLE customer DROP CONSTRAINT customer_id_new_not_null;
ALTER TABLE orders   DROP CONSTRAINT orders_customer_id_new_not_null;

-- 3. orders: drop the old column (takes the old FK and index with it), promote the new one.
-- move FOREIGN KEY and its index to the new column (validated FOREIGN KEY).
ALTER TABLE orders DROP COLUMN customer_id;
ALTER TABLE orders RENAME COLUMN customer_id_new TO customer_id;
ALTER TABLE orders RENAME CONSTRAINT orders_customer_id_new_fk TO orders_customer_id_fkey;
ALTER INDEX orders_customer_id_new_idx RENAME TO orders_customer_id_idx;

-- 4. customer: move the identity to the new column.
ALTER TABLE customer ALTER COLUMN id DROP IDENTITY;
ALTER TABLE customer ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;

-- 5. customer: swap the primary key.
ALTER TABLE customer DROP CONSTRAINT customer_pkey;
ALTER TABLE customer DROP COLUMN id;
ALTER TABLE customer RENAME COLUMN id_new TO id;
ALTER TABLE customer ADD CONSTRAINT customer_pkey PRIMARY KEY USING INDEX customer_id_new_uq; -- customer_id_new_uq: using new index
ALTER SEQUENCE customer_id_new_seq RENAME TO customer_id_seq; -- customer_id_new_seq: created auto as new identity column

-- 6. Continue the identity where the old one stopped.
SELECT setval('customer_id_seq', (SELECT last_value FROM _identity_position));
